# MySQLデータベースとGoバックエンドを定義する
version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: todo_app
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - todo-network
    ports:
      - "3306:3306"
  
  backend:
    build: ./backend
    container_name: todo-backend
    command: ["go", "run", "main.go"]
    working_dir: /app
    volumes:
      - ./backend:/app
    networks:
      - todo-network
    ports:
      - "8080:8080"
    depends_on:
      - db

networks:
  todo-network:
    driver: bridge